services:
  inventario:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres_inventario
      - DB_NAME=inventario_db
      - DB_USER=postgres
      - DB_PASS=postgres
      - PORT=3001
      - DB_PORT=5432
    networks:
      - ventas-network
    depends_on:
      - postgres_inventario

  postgres_inventario:
    image: postgres:14-alpine
    ports:
      - 5437:5432
    environment:
      - POSTGRES_DB=inventario_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata_inventario:/var/lib/postgresql/data
    networks:
      - ventas-network

volumes:
  pgdata_inventario:


networks:
  ventas-network:
    driver: bridge

